### ISSUE TITLE
Is the hash mode supported?

### ISSUE THREAD

**Issue by ListeningRift** [EmilTholin/svelte-routing#102]
Excuse me， does this plugin support the hash mode of the history API?

**Comment by EmilTholin** [comment]
Hi @ListeningRift!

This router sadly doesn't support the hash mode, so what is said in https://github.com/EmilTholin/svelte-routing/issues/24 still stands. It was buggy and incredibly difficult to get all the edge cases right, so we opted to remove it in the `1.0.0` since the absolute majority of users didn't use that functionality.

**Comment by ListeningRift** [comment]
Thank you, I was faced with a small project, but there were some compatibility requirements. Thank you  very much!
