### ISSUE TITLE
routing problem with transitions

### ISSUE THREAD

**Issue by gaou-piou** [EmilTholin/svelte-routing#107]
If a component has in, out transitions then routing is not completed.
Take a look at this example

https://codesandbox.io/s/test-svelte-routing-with-transitions-tm0yd

**Comment by nodefish** [comment]
I think this is a known svelte bug. In most cases it happens because the parent of a transitioning component was unmounted.

By default, parent mount/unmount triggers child transitions. This is often something you want. But you can mark transitions as `local` to disable this behavior, which sometimes can fix the issue:

`transition:fade|local={{..}}`

**Comment by clockelliptic** [comment]
is this issue sufficiently resolved on account of @nodefish 's feedback?

**Comment by EmilTholin** [comment]
Closing this as it was (is?) an issue upstream in Svelte that we sadly have no control over in this library.
