### ISSUE TITLE
Theming support via classes?

### ISSUE THREAD

**Issue by kamiyaa** [EmilTholin/svelte-routing#129]
It doesn't seem like `<Link/>` class tag is working?
If not, are there other ways to theme `<Link/>`?

**Comment by ronvdberkmortel** [comment]
I had the same problem and ended up using a NavLink component to add the relevant classes. Props to Emil for the package and the example that provided the base code. Since I am using Bootstrap 4 in combination with svelte-routing, I wanted to add the base _nav-link_ class and conditionally add the _active_ class.

**components/NavLink.svelte**
```
<script>
  import { Link } from "svelte-routing";

  export let to = "";

  function getProps({ location, href, isPartiallyCurrent, isCurrent }) {
    const isActive = href === "/" ? isCurrent : isPartiallyCurrent || isCurrent;

    // The object returned here is spread on the anchor element's attributes
    if (isActive) {
      return { class: "nav-link active" };
    }
    return { class: "nav-link" };
  }
</script>

<Link {to} {getProps}>
  <slot />
</Link>
```

**App.svelte**
```
  import NavLink from "./components/NavLink.svelte";
  ...
          <li class="nav-item">
            <NavLink to="/">Home</NavLink>
          </li
  ...
```

Hopefully this is useful to you and other users of the package.

**Comment by download13** [comment]
Could we just take the [active action from svelte-spa-router](https://github.com/ItalyPaleAle/svelte-spa-router/blob/master/active.js)?

I like their solution to this, but want to use the path-based routing of this library over the fragment-based routing of the other.

Both projects are under the MIT license, so that shouldn't be an issue.

**Comment by nhe23** [comment]
A pretty simple solution would be to have a prop "className" in Link.svelte which can be set from the outside and which is used to set the class of the link.

**Link.svelte** would then look like this:
`<script>
  import { getContext, createEventDispatcher } from "svelte";
  import { ROUTER, LOCATION } from "./contexts.js";
  import { navigate } from "./history.js";
  import { startsWith, resolve, shouldNavigate } from "./utils.js";

  export let to = "#";
  export let replace = false;
  export let state = {};
  export let getProps = () => ({});
  export let className;

 ...
</script>


<a class={className} href="{href}" aria-current="{ariaCurrent}" on:click="{onClick}" {...props}>
  <slot></slot>
</a>
`

**Comment by EmilTholin** [comment]
Hi @kamiyaa!

Like @ronvdberkmortel pointed out the `getProps` prop function is used to give the underlying anchor tag custom attributes, but I will have to consider if all the extra props on the `Link` should be spread on the anchor tag as well for simplicity's sake. I'm not quite sure if there are any drawbacks to that at the moment, but I will look into it.

**Comment by guidobouman** [comment]
I think that would be great. It would provide more familiarity to people coming from Vue & React. They expect non-used props to be passed to the underlying anchor.

**Comment by guidobouman** [comment]
Can I maybe help you out here?

**Comment by guidobouman** [comment]
Oh, it's already solved on: https://github.com/EmilTholin/svelte-routing/pull/128

**Comment by EmilTholin** [comment]
Hi @kamiyaa!

Since [`1.5.0` all extra properties given to the `Link` component are passed as attributes to the underlying `a` tag](https://github.com/EmilTholin/svelte-routing/pull/128).
