### ISSUE TITLE
various questions : usage, and rollup bundle size too big

### ISSUE THREAD

**Issue by hefeust** [EmilTholin/svelte-routing#15]
HI,

I'm trying to use svelte, which is promising lib, in conjunction with your svelte-routing plugin. Here are a few quesitons :

* Why do I need to place other views than Home in data field of App.svelte ? Is it because they aren'y loaded initialiy ?

* since I use svelte-*routing, my bundle size jumped from 500sloc up to 35600sloc... and 200ko ! how does it possible ? This overcost is painful... Am I doing something wrong ?

Thanks for reply.

Notice: my post on stackoverflow about rollup-plugin-import-, which exposes my actial config :

https://stackoverflow.com/questions/54159984/rollup-svelte-typescript-couldnt-use-rollup-plugin-import-alias

Elsewhere, happily, it works.

**Comment by hefeust** [comment]
EDIT on my issue :+1: 

the big size is due to inclusion of history.js, I apologized, I have under-estimated the complexity of the problems this lib solves... of course, in a 3 pages hello world app it takes room, but in a real-world app with dozen of views, it could disappear slightly (in weight %, I mean) !

**Comment by EmilTholin** [comment]
Hey @hefeust!

> Why do I need to place other views than Home in data field of App.svelte ? Is it because they aren'y loaded initialiy ?

If you are referring to `About` and `Blog` in the README, it's just an example showing how to render different components for the paths `/about` and `/blog` than what is rendered on the root path `/`.

> since I use svelte-*routing, my bundle size jumped from 500sloc up to 35600sloc... and 200ko ! how does it possible ? This overcost is painful... Am I doing something wrong ?

As you noted in your second comment, `history` is a pretty heavy library that this library uses under the hood. A lot of that code will be shaken of in production, since you are never using all of it in one app, so your live app will not be as heavy as the development version one.

It's still a pretty heavy library though, and that is why we will most likely remove the `history` dependency in `1.0.0` when Svelte v3 comes out, and roll our own implementation like [`reach-router`](https://github.com/reach/router/blob/master/src/lib/history.js) does.
