### ISSUE TITLE
Resolve href for <a>s with use:link?

### ISSUE THREAD

**Issue by user896724** [EmilTholin/svelte-routing#150]
`<Link to=href>...</Link>` resolves the href according to `basepath`, but `<a {href} use:link>...</a>` keeps the href as-is.  Is there a reason for this discrepancy?

**Comment by mustafa0x** [comment]
Possibly related: `<Link>` navigates with the query string, but `use:link` doesn't.

**Comment by mefechoel** [comment]
@user896724 In Svelte, actions cannot access context. Svelte routing uses context under the hood, so a `Link` for example knows, which `Router` it is in. It can then access that `Router`s `basepath` and resolve the path accordingly. Since `use:link` is an action, it has no way of accessing context and can therefore unfortunately not resolve its `href`.

**Comment by user896724** [comment]
Thanks @mefechoel
