### ISSUE TITLE
Question: can i use state with use:links?

### ISSUE THREAD

**Issue by jimmywarting** [EmilTholin/svelte-routing#154]
```html
<Link {to} {state}>text</Link>
```
...works just fine but.

But this dosen't:
```html
<div use:links>
  <a {href} {state}>text</a>
</div>
``` 
anyway to still use `<a>` and also use state at the same time?

**Comment by EmilTholin** [comment]
Hi @jimmywarting!

This is sadly not possible at the moment since the [`link` and `links` actions does a `navigate` call under the hood and only supplies the `replace` property](https://github.com/EmilTholin/svelte-routing/blob/4582a86a0c8067c5599a5ca7809933d0012ae9cd/src/actions.js#L72). I'm not sure an arbitrary JavaScript object could be passed to a `a` tag and used in this call, since Svelte uses it as an attribute directly rather than a component prop.

I will look into if there is any way to get this working and get back to you, but my guess is that it will not be possible to implement.

**Comment by krishnaTORQUE** [comment]
Not sure what you are trying to accomplish but this might help.

```svelte
<div on:click={() => navigate(href)}>
    <a {href} {state}>text</a>
</div>
```
