### ISSUE TITLE
Question: Possible to use hash routing?

### ISSUE THREAD

**Issue by markschellhas** [EmilTholin/svelte-routing#164]
Hi,
My app will be embeded on a site and we need to navigate to different states of the app — hash routing would be great for this use case. 

I saw this issue from 2 years ago and there's been a comment 11 months ago, but no response to whether this is possible with svete-routing? https://github.com/EmilTholin/svelte-routing/issues/13

Cheers

**Comment by mefechoel** [comment]
It is currently not possible to use hash based routing with svelte-routing.

I released a fork of svelte-routing called [svelte-navigator](https://github.com/mefechoel/svelte-navigator) which allows for more configuration. You could use it with a memory based history, which would probably suit your use case if you don't care that the apps state is persisted in the url ([see the custom history docs](https://github.com/mefechoel/svelte-navigator#custom-history)).
It also supports a custom history, which actually allows for a hash history (see the link before or the [hash history example in the repl](https://svelte.dev/repl/195011a49a714e22b1a335037e124458)).
I am also planning to add an official hash history implementation in the next version. I'm gonna publish a roadmap for that soon.

Another popular router that uses hash based routing is [svelte-spa-router](https://github.com/ItalyPaleAle/svelte-spa-router). It has an api which is more like vue-router, rather than svelte-routing or svelte-navigator, which are more like react-router. I guess it's up to personal taste and which style you're most comfortable with...

**Comment by markschellhas** [comment]
@mefechoel ok, I'll check those options out - very helpful, thank you!
