### ISSUE TITLE
How to send a 404 status.

### ISSUE THREAD

**Issue by Misly16** [EmilTholin/svelte-routing#165]
Hi, so I have Integrated a 404 page but it sends a 200 status, would it be possible to send the 404 status?

**Comment by mefechoel** [comment]
I don't think this is possible. For server side rendering, you'd need to know about all `Route` components you defined in your app. But the server rendered html can not communicate anything about its contents back to you.
If you duplicate all your route paths in your server code, you could theoretically match incoming requests against these routes and decide if you send a 404 or if you render the app.
This will however not work when using client side routing. If you've already loaded the app in your browser and then for example click a broken link, the `Router` will try to match a `Route` and fail. You can supply a fallback route to display an error page, but since the app is already loaded it won't make a request to the server and there is no 404 status to send.

**Comment by Misly16** [comment]
Hey there, thank you very much for the response!
