### ISSUE TITLE
Navigate has bugs for me.

### ISSUE THREAD

**Issue by rjpruitt16** [EmilTholin/svelte-routing#176]
I have a nest Router. I am using firebase authentication to verify if the user is signed in. The url will change in browser but the page will not change. I can tell the route exist because I can click the refresh button and I can see the actual page. I can traverse the routes well with the via href but navigate has buggy behavior. 
```
<script>
....
const unsubscribe = userStore.subscribe(user => {
    if (!user) {
      navigate("/auth/login/", {replace: "true"});
    } else if (!isOnboardingComplete) {
      navigate("/auth/onboard/", {replace: "true"});
    }
</script>
...

```

Also on that page, I am rendering and image dynamically, and it does not show when using navigate() either. Any advice?

```
 <div
        class="absolute top-0 w-full h-full bg-gray-900 bg-no-repeat bg-full"
        style="background-image: url({registerBg2});"
      ></div>

```

**Comment by mefechoel** [comment]
I think this is a bug with the `Router`. It swollows changes to the locatiom that occure before its `onMount` runs (See [related issue in svelte-navigator](https://github.com/mefechoel/svelte-navigator/issues/16) and #59). 
This should probably be fixed in this library, but as a workaround you can try moving your subscription and navigating into an `onMount` handler.

I don't know what the issue wit the image could be though, could you provide a little more imfornation on that?

**Comment by rjpruitt16** [comment]
I see the problem. When I use navigate, node js or rollup will try to find update the path to http://localhost:5000/auth/assets/img/register_bg_2.png, but the image path should remain as http://localhost:5000/assets/img/register_bg_2.png,

**Comment by rjpruitt16** [comment]
My apologies. I was wrong. A bug unrelated to navigate was the problem. It just seem like it was coming from navigate function.
