### ISSUE TITLE
How to do a 404?

### ISSUE THREAD

**Issue by bigjoevtrj** [EmilTholin/svelte-routing#18]
Self explanatory title.

**Comment by EmilTholin** [comment]
Hi @bigjoevtrj!

A `Route` component without a given `path` property will be rendered if there is no other `Route` in the `Router` that matches.

```html
<Router>
  <Route path="blog" component="{Blog}" />
  <Route path="about" component="{About}" />
  <Route component="{NotFound}" />
</Router>
```

**Comment by bigjoevtrj** [comment]
> Hi @bigjoevtrj!
> 
> A `Route` component without a given `path` property will be rendered if there is no other `Route` in the `Router` that matches.
> 
> ```
> <Router>
>   <Route path="blog" component="{Blog}" />
>   <Route path="about" component="{About}" />
>   <Route component="{NotFound}" />
> </Router>
> ```

This isn't working for me...

I need to have a something like this

```
<Router>
    <Route path="/" component={Index} />
    <Route path="/:id" component={Show} />
    <Route path="/:id/edit" component={Edit} />
    <Route component={NotFound} />
</Router>
```

I'd tried and it renders the Index component.

**Comment by bigjoevtrj** [comment]
@EmilTholin an exact prop should resolve this problem, so we can use it like this:

```
<Router>
    <Route path="/" exact component={Index}/>
    <Route path="/:id/edit" component={Edit}/>
    <Route path="/:id" component={Show}/>
    <Route component={NotFound}/>
</Router>
```

/users === exact then Index
/users/10/edit then Edit
/users/10 then Show
/users/groups then NotFound

**Comment by EmilTholin** [comment]
Sorry to keep you waiting @bigjoevtrj.

The example that I wrote in my first comment works and shows the `NotFound` route for any other route than `/blog` and `/about`, but you're right that the `/` route always takes precedence over the `NotFound` route, and that's a bug. Great find!

The reason for this is because every route path gets [a wildcard `*` added to it it](https://github.com/EmilTholin/svelte-routing/blob/f6a538a5d5cb8e74de0f776e7584c81eb1853f7f/src/utils.js#L307-L316) to make it so every route is still rendered when it is a partial match. E.g. `/blog` should be rendered when `/blog/first` is selected [in the example project in this repository](https://github.com/EmilTholin/svelte-routing/blob/f6a538a5d5cb8e74de0f776e7584c81eb1853f7f/example/src/routes/Blog.svelte#L14-L28).

Because of this the `/` route is treated as `/*` under the hood, and that will always be a better match than `NotFound`. It should remove the bug if we treat `/` as a special case and don't add a `*` to it, but I have to look into it a bit more before I can add such a fix so that I don't destroy anything else.

**Comment by bigjoevtrj** [comment]
Hi, thanks for replying!

IMHO treat "/" as a special case and don't add "*" to it is not the best approach, since in some cases people doesn't want to have a 404 route and can automatically use "/" as a fall back, but add an exact prop and then don't add "*" to this route sounds perfect or you can have a route with a prop "fallback" and use it on a non match route, if fallback doesn't exists keep using best pick.

**Comment by bravecow** [comment]
Maybe that without route template (`/:name` or something) path means single route. there are so many routers that this behavior can be borrowed from others and not to reinvent wheels.

**Comment by jacwright** [comment]
I believe we still need an `exact` attribute or equivalent. If I have a path `/blog/:slug` and someone goes to `/blog/some-post/comments` I would want it to show a 404, not display the blog post. I actually use the exact much more than wildcards.

With that in mind, I recommend making the wildcard explicit. `/blog/*` instead of just `/blog`. Thoughts?

**Comment by EmilTholin** [comment]
@jacwright Yes, I think you are right. I've been having the same thoughts lately, but have not committed to it yet.

Removing [this `/*`](https://github.com/EmilTholin/svelte-routing/blob/77bd791e616d24b93d16b11a1c54e9e96c4c5a32/src/utils.js#L318) and requiring explicit `/*` from the user (e.g. [`blog/*` here](https://github.com/EmilTholin/svelte-routing/blob/77bd791e616d24b93d16b11a1c54e9e96c4c5a32/example/src/App.svelte#L20)) would potentially be a breaking change, but I think it will be worth it.

**Comment by bigjoevtrj** [comment]
@EmilTholin other thing that I miss and you could think about is something like this:

```
<Filters {criteria} />
<Router>
    <Route path="/comments" component={CommentsReport}  {criteria} />
    <Route path="/invoices" component={InvoicesReport} {criteria} />
</Router>
```

Parameters passed to ROUTE forward to the Component.

**Comment by EmilTholin** [comment]
Sorry for the delay @bigjoevtrj.

This was [fixed in `1.1.2`](https://github.com/EmilTholin/svelte-routing/commit/363bd15b6447e9c2d60db17f1464ac9955e85ff9). You now have to explicitly give a `/*` to a `Route` path in order for it to be able to render child `Router`s so that a 404 can be rendered.

```html
<Router url="{url}">
  <Route path="about" component="{About}" />
  <!-- Will be able to have a Router of its own -->
  <Route path="blog/*" component="{Blog}" />
  <Route path="/" component="{Home}" />
</Router>
```

```html
<Router url="{url}">
  <Route path="about" component="{About}" />
  <Route path="blog" component="{Blog}" />
  <Route path="/" component="{Home}" />
  <!-- Will be rendered if the path differs from /about, /blog or /. -->
  <Route component={NotFound} />
</Router>
```

**Comment by bigjoevtrj** [comment]
"*" now is passed to component as prop
```
<App> was created with unknown prop '*'
```

CODE:
```
<Router>
    <Route path="/" component={ Login } />
    <Route path="/app/*" component={ App } />
</Router>
```

**Comment by EmilTholin** [comment]
@bigjoevtrj Stop writing unrelated stuff in a closed issue. This has already been discussed [here](https://github.com/EmilTholin/svelte-routing/issues/43).

**Comment by nickyhajal** [comment]
@EmilTholin 

Is there a way for `<Route path="blog/*" component="{Blog}" />` to match "/blog" _and_ "/blog/*"?

I have an admin route:

` <Route path="admin" component="{AdminLayout}" />`

The admin layout has its own router and a consistent sidebar. If I navigate to a sub-page "admin/metrics", the route doesn't match, so I add:

` <Route path="admin/*" component="{AdminLayout}" />`

Now, if I navigate between subpages, everything is great. But, if you navigate back to "/admin", the UI flashes as it reloads the AdminLayout compontent

Ideally I could do something like

` <Route path="admin*" component="{AdminLayout}" />`

Which matches "/admin" _and_ "/admin/<subpages" with a single route, so AdminLayout would be reused between all of them.

Thanks!
