### ISSUE TITLE
Installing as dev dependency?

### ISSUE THREAD

**Issue by ArtemKolichenkov** [EmilTholin/svelte-routing#19]
In README.md it says to install svelte-routing to runtime dependencies.
`npm install --save svelte-routing`
Example project also has everything (even Svelte and Rollup) under dependencies.

Aren't we supposed to install everything to devDependencies like Svelte templates [(#1](https://github.com/sveltejs/template/blob/master/package.json), [#2](https://github.com/sveltejs/template-webpack/blob/master/package.json)) and [Sapper](https://github.com/sveltejs/sapper/blob/master/package.json) do?

**Comment by EmilTholin** [comment]
Hi @ArtemKolichenkov!

The reason why Svelte is listed in `devDependencies` is because it's a compiler and isn't included in the resulting code you ship to your users. `svelte-routing` on the other hand is a runtime library that needs to be shipped to your users.

It really doesn't matter how you decide to install your dependencies in your app. It's much more important if you are writing a library that should only ship the `dependencies` with your library code, and use `devDependencies` for the development of the library.

**Comment by ArtemKolichenkov** [comment]
But you're not shipping built bundle.js via npm, you're shipping source code with `.svelte` files, i.e. components that are not yet compiled. I thought it was supposed to be devDependencies for uncompiled things.
Svelte repo might better place to ask that question though. 😅

**Comment by EmilTholin** [comment]
Yes, you're right in that this library only points to the uncompiled `src/index.js` file, but the final bundle of JavaScript *you* send to your users will contain the `svelte-routing` runtime.

But again, it doesn't really matter if you use `dependencies` or `devDependencies` when you build apps.

**Comment by ArtemKolichenkov** [comment]
Makes sense. Thanks! 🙂  I'll close the issue.
