### ISSUE TITLE
Hash-based history removed?

### ISSUE THREAD

**Issue by ItalyPaleAle** [EmilTholin/svelte-routing#24]
Version 1 removed one of the main features I depended on, hash-based history. This is very important to us building apps that aren't PWAs, and need to store history state in hashes. This includes, for examples, static apps that don't have a server to do SSR.

Any chance you could restore that feature?

**Comment by EmilTholin** [comment]
Hi @ItalyPaleAle!

Yes, hash-based routing was removed in `1.0.0`, and is not coming back.

[We currently only create an in-memory mock of the browser `history` API if the library is used outside of the DOM, in tests for example](https://github.com/EmilTholin/svelte-routing/blob/f6a538a5d5cb8e74de0f776e7584c81eb1853f7f/src/history.js#L98-L108). We could expose the history creation mechanism [like Reach Router does](https://github.com/reach/router/issues/25#issuecomment-394003652) so that you can use a memory router if that should be useful.

If in-memory routing is not enough, and you really need hash-based routing, you will have to use another library or fork it and add it to your version. You could [use the `createMemorySource`](https://github.com/EmilTholin/svelte-routing/blob/f6a538a5d5cb8e74de0f776e7584c81eb1853f7f/src/history.js#L61-L96) as a starting point for implementing a `createHashSource`.

**Comment by ItalyPaleAle** [comment]
This is very unfortunate. There are many situations where hash-based history is preferred or even required.

The way the code enables memory-based history right now seems to be by looking if the DOM is available. There’s no switch or other way to change that. It doesn’t even test for the availability of the HTML5 history API...

Memory-based could work but it would make it impossible for users to refresh the page.

**Comment by EmilTholin** [comment]
Sounds like memory-based routing will not be enough for your use case either. We don't have the manpower or interest in dealing with all the edge cases that hash-based routing entails.

I reiterate that it shouldn't be too hard to add a `createHashSource` to a fork of your own.

**Comment by ItalyPaleAle** [comment]
I ended up writing my own component. Making it work with this, which includes things such as SSR support, seemed just more cumbersome.

https://github.com/ItalyPaleAle/svelte-spa-router If anyone finds this thread :)

**Comment by xamgore** [comment]
@EmilTholin could you explain why did you remove hash-based routing?

**Comment by vedmant** [comment]
Yeah, it's unfortunate that this pacakage is not supporting hash based routing, this is essential feature for a router. That's the only reason why I can't use this package.

**Comment by SupremeTechnopriest** [comment]
Would be nice to have this for running inside electron.  Navigator History breaks it.

**Comment by benbucksch** [comment]
It is very unfortunate that hash based routing is not supported.

I like your declarative API for the router very much. (I also liked React Router before this, for the same reason.) I much prefer this over alternative ways to declare routes, e.g. as JSON or as filename conventions. Your declarative approach feels the cleanest.

However, I do need hash routing, because I want to host the application on a static web server, for server security and server performance reasons. Given that many routing libraries offer the choice, I kept looking for a way to configure this here. At least thanks for the clear statement. Would be nice to have a similarly clear statement on the main website, with a pointer to a suitable alternative.

I have found https://github.com/mefechoel/svelte-navigator/tree/main/example/custom-hash-history , thanks to #164 . It would be nice to maybe list that on your main page as hash-based alternative.

It's a pity, because I was very happy with your library and wanted to stay with it.
