### ISSUE TITLE
`TypeError: Cannot read properties of undefined (reading 'default')` after upgrading to `2.2.0`

### ISSUE THREAD

**Issue by Saibamen** [EmilTholin/svelte-routing#262]
`at Router.svelte:45:28`

Line 45: `if (default_slot) default_slot.c();`

This runtime error was introduced in svelte-routing 2.2.0.

Version 2.1.0 is OK.

Related: https://github.com/EmilTholin/svelte-routing/pull/258

**Comment by krishnaTORQUE** [comment]
`svelte` version: ??
`svelte-routing` version: ??

**Comment by krishnaTORQUE** [comment]
Can you please try latest version of `svelte-routing`?

**Comment by Saibamen** [comment]
This same bug in `2.5.0`

**Comment by krishnaTORQUE** [comment]
@motzel Could you please have look, Thanks

**Comment by motzel** [comment]
This line in the source code is completely different. The only places where the ``default`` property is read are:

https://github.com/EmilTholin/svelte-routing/blob/2673fe7c5a76d079a879f3f3a8dd03db9183b2f3/src/Router.svelte#L52
https://github.com/EmilTholin/svelte-routing/blob/2673fe7c5a76d079a879f3f3a8dd03db9183b2f3/src/utils.js#L33
https://github.com/EmilTholin/svelte-routing/blob/2673fe7c5a76d079a879f3f3a8dd03db9183b2f3/src/utils.js#L100

and none of them were changed in my PR. My guess is that the problem is in either of the last two, because the ``pick()`` function is used in ``Router.svelte``. But I'm not able to reproduce it, it works for me.

@Saibamen Could you prepare a minimal example in which this bug appears? Or just replace ``route.default`` in these two lines in ``utils.js`` with ``route?.default`` and please check if it works.

**Comment by Saibamen** [comment]
Full stacktrace (version 2.2.0):

```
Uncaught TypeError: Cannot read properties of undefined (reading 'default')
    at Router.svelte:45:28
    at sync (index.js:150:19)
    at index.js:173:3
    at Object.subscribe2 [as subscribe] (index.js:82:11)
    at subscribe (utils.js:139:22)
    at component_subscribe (utils.js:159:31)
    at instance3 (Router.svelte:34:28)
    at init (Component.js:135:5)
    at new Router (Router.svelte:96:54)
    at create_fragment (Navigation.svelte:17:15)
```

**Comment by Saibamen** [comment]
@motzel: I added `?` to `utils.js` and `Router.svelte` and nothing was changed.
Error and stack trace is the same

**Comment by motzel** [comment]
@Saibamen This is all the way impossible, because there is no other reading of ``default`` property in the whole svelte-routing code. And even more so in line 45 of Router.svelte, because there is something else there. Could you please show the full stacktrace with the error? Although some minimal example of where the error occurs would be best.

**Comment by motzel** [comment]
Oh, I didn't notice that you already added the full stacktrace (I'm on mobile now), sorry

**Comment by Saibamen** [comment]
@motzel: Working version: https://github.com/Saibamen/svelte-routing-example/tree/2-1-0_working

![image](https://github.com/EmilTholin/svelte-routing/assets/905878/29c02db8-2312-41e1-a73b-1682dd0968b7)

Upgrade `svelte-routing` to version 2.2.0 and it will have this exception.

**Comment by motzel** [comment]
Thanks! I'll check it out today after work (~in 8h)
