### ISSUE TITLE
is this project even compiled?

### ISSUE THREAD

**Issue by shavyg2** [EmilTholin/svelte-routing#52]
I don't see anything that compiles the code. This is gonna work locally, but onces published to npm it needs to be compiled because, svelte is not going to compile, files inside the node_modules directory.

**Comment by EmilTholin** [comment]
Hi @shavyg2!

No, this project is not compiled. The components of `svelte-routing` have to be compiled together with the rest of your app, which is why we only publish the `.svelte` source files. You can look at the [example project in this repository](https://github.com/EmilTholin/svelte-routing/blob/master/example/rollup.config.js) for a way to go about it.
