### ISSUE TITLE
Is it ok to use  window.location.assign("/"); with this router?

### ISSUE THREAD

**Issue by QuantumInformation** [EmilTholin/svelte-routing#90]
Example code:

![image](https://user-images.githubusercontent.com/216566/70174675-45994200-16cd-11ea-9976-d4d07a408f36.png)

**Comment by EmilTholin** [comment]
Hi @QuantumInformation!

Using `window.location.assign` will cause a full load of the page from the server rather than navigating in the browser, which might not be what you want.

You can use the [`navigate`](https://github.com/EmilTholin/svelte-routing#navigate) method instead if you want to just navigate in the browser.
